version: '3.4'

services:
  my_mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: rooot 
      MTSQL_DATABASE: first-docker
    ports: 
      - '3001:3001'
    volumes: 
      - my_volume:/var/lib/mysql 
  web:
    build: .
    depends_on: 
      - "db"
    command: //よく分かっていない
  db: 
    image: mysql:5.6
  
  dockerexpress:
    image: dockerexpress
    build:
      context: .
      dockerfile: ./Dockerfile
    
    ports:
      - 3000:3000
volumes:
  my_volume:
